apiVersion: v1
kind: Service
metadata:
  name: mobi-backend
  namespace: mobi-dev
spec:
  selector:
    app: mobi-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
