apiVersion: v1
kind: Service
metadata:
  name: mobi-frontend
  namespace: mobi-dev
spec:
  selector:
    app: mobi-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
